# Generated by Django 4.2.7 on 2025-03-30 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Legislator',
            fields=[
                ('legislator_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=50)),
                ('chamber', models.CharField(choices=[('House', 'House'), ('Senate', 'Senate')], max_length=50)),
                ('party', models.CharField(choices=[('Democrat', 'Democrat'), ('Republican', 'Republican'), ('Independent', 'Independent')], max_length=50)),
                ('total_posts_tw', models.IntegerField(default=0)),
                ('total_likes_tw', models.IntegerField(default=0)),
                ('total_retweets_tw', models.IntegerField(default=0)),
                ('total_misinfo_count_tw', models.IntegerField(default=0)),
                ('total_interactions_tw', models.IntegerField(default=0)),
                ('interaction_score_tw', models.FloatField(default=0)),
                ('overperforming_score_tw', models.FloatField(default=0)),
                ('civility_score_tw', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('text', models.TextField()),
                ('attachment', models.URLField(blank=True, null=True)),
                ('state', models.CharField(max_length=50)),
                ('chamber', models.CharField(max_length=50)),
                ('party', models.CharField(max_length=50)),
                ('retweet_count', models.IntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('count_misinfo', models.IntegerField(default=0)),
                ('civility_score', models.FloatField(blank=True, null=True)),
                ('interaction_score', models.FloatField(blank=True, null=True)),
                ('overperforming_score', models.FloatField(blank=True, null=True)),
                ('legislator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='civicwatch.legislator')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='civicwatch.post')),
            ],
        ),
        migrations.CreateModel(
            name='LegislatorInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('interaction_type', models.CharField(choices=[('mention', 'Mention'), ('reply', 'Reply'), ('share', 'Share')], max_length=20)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civicwatch.post')),
                ('source_legislator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_interactions', to='civicwatch.legislator')),
                ('target_legislator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_interactions', to='civicwatch.legislator')),
            ],
        ),
    ]
